spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: ${POSTGRES_SCHEMA}
      connection-timeout: ${POSTGRES_CONNECTION_TIMEOUT}
      maximum-pool-size: ${POSTGRES_MAX_POOL_SIZE}
    username: '${POSTGRES_USER}'
    password: '${POSTGRES_PASSWORD}'
    url: jdbc:postgresql://${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/${POSTGRES_DB}?currentSchema=${POSTGRES_SCHEMA}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: false

catalog:
  greeting-message: "Welcome to bazinga's books catalog!"
  test-data:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: refresh,threads,metrics,health

logging:
  level:
    com.bazinga.eg.catalogservice: warn
    org.springframework.boot: warn
    org.springframework.web: warn