spring:
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/${POSTGRES_DB}?currentSchema=${POSTGRES_SCHEMA}
    username: '${POSTGRES_USER}'
    password: '${POSTGRES_PASSWORD}'
    pool:
      initial-size: ${POSTGRES_CONNECTION_POOL_INITIAL_SIZE}
      max-size: ${POSTGRES_CONNECTION_POOL_MAX_SIZE}
      max-create-connection-time: ${POSTGRES_CONNECTION_POOL_MAX_CREATE_CONNECTION_TIME}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: false

management:
  endpoints:
    web:
      exposure:
        include: refresh,threads,metrics,health

logging:
  level:
    com.bazinga.eg.orderservice: warn
    org.springframework.boot: warn
    org.springframework.web: warn